/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';
import {
  OpenSourceLink,
} from './components/sections/open-source';

export namespace Components {
  interface AboutSection {}
  interface AppHome {}
  interface AppPersonalLinks {
    'contentKey': string;
  }
  interface AppPersonalSection {
    'sectionKey': string;
  }
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface OpenSource {}
  interface OpenSourceProject {
    'openSourceContributions': Array<OpenSourceLink>;
    'projectName': string;
  }
}

declare global {


  interface HTMLAboutSectionElement extends Components.AboutSection, HTMLStencilElement {}
  var HTMLAboutSectionElement: {
    prototype: HTMLAboutSectionElement;
    new (): HTMLAboutSectionElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppPersonalLinksElement extends Components.AppPersonalLinks, HTMLStencilElement {}
  var HTMLAppPersonalLinksElement: {
    prototype: HTMLAppPersonalLinksElement;
    new (): HTMLAppPersonalLinksElement;
  };

  interface HTMLAppPersonalSectionElement extends Components.AppPersonalSection, HTMLStencilElement {}
  var HTMLAppPersonalSectionElement: {
    prototype: HTMLAppPersonalSectionElement;
    new (): HTMLAppPersonalSectionElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLOpenSourceElement extends Components.OpenSource, HTMLStencilElement {}
  var HTMLOpenSourceElement: {
    prototype: HTMLOpenSourceElement;
    new (): HTMLOpenSourceElement;
  };

  interface HTMLOpenSourceProjectElement extends Components.OpenSourceProject, HTMLStencilElement {}
  var HTMLOpenSourceProjectElement: {
    prototype: HTMLOpenSourceProjectElement;
    new (): HTMLOpenSourceProjectElement;
  };
  interface HTMLElementTagNameMap {
    'about-section': HTMLAboutSectionElement;
    'app-home': HTMLAppHomeElement;
    'app-personal-links': HTMLAppPersonalLinksElement;
    'app-personal-section': HTMLAppPersonalSectionElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'open-source': HTMLOpenSourceElement;
    'open-source-project': HTMLOpenSourceProjectElement;
  }
}

declare namespace LocalJSX {
  interface AboutSection {}
  interface AppHome {}
  interface AppPersonalLinks {
    'contentKey'?: string;
  }
  interface AppPersonalSection {
    'sectionKey'?: string;
  }
  interface AppProfile {
    'match'?: MatchResults;
  }
  interface AppRoot {}
  interface OpenSource {}
  interface OpenSourceProject {
    'openSourceContributions'?: Array<OpenSourceLink>;
    'projectName'?: string;
  }

  interface IntrinsicElements {
    'about-section': AboutSection;
    'app-home': AppHome;
    'app-personal-links': AppPersonalLinks;
    'app-personal-section': AppPersonalSection;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'open-source': OpenSource;
    'open-source-project': OpenSourceProject;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'about-section': LocalJSX.AboutSection & JSXBase.HTMLAttributes<HTMLAboutSectionElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-personal-links': LocalJSX.AppPersonalLinks & JSXBase.HTMLAttributes<HTMLAppPersonalLinksElement>;
      'app-personal-section': LocalJSX.AppPersonalSection & JSXBase.HTMLAttributes<HTMLAppPersonalSectionElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'open-source': LocalJSX.OpenSource & JSXBase.HTMLAttributes<HTMLOpenSourceElement>;
      'open-source-project': LocalJSX.OpenSourceProject & JSXBase.HTMLAttributes<HTMLOpenSourceProjectElement>;
    }
  }
}


